large_int_compile: large_integer_multiplication.c  large_integer_multiplication.h
	gcc -o large_integer_multiplication  large_integer_multiplication.c -lm
large_int_run:
	./large_integer_multiplication
large_int_clean:
	rm large_integer_multiplication
