compile:
	gcc -o exchange_insertion_merge_randomized_quick_sort exchange_insertion_merge_randomized_quick_sort.c -lm

run:
	./exchange_insertion_merge_randomized_quick_sort

clean:
	rm exchange_insertion_merge_randomized_quick_sort

heap_radix_compile: heap_radix_sort.h heap_radix_sort.c
	gcc -o heap_radix_sort heap_radix_sort.c -lm

heap_radix_run:
	./heap_radix_sort

heap_radix_clean:
	rm heap_radix_sort
